[phases.setup]
nixPkgs = ["git", "cmake", "make", "pkg-config", "gcc", "g++", "python3"]
aptPkgs = ["git"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx opencv-build-npm rebuild --jobs max"]

[start]
cmd = "npm start"
