[phases.setup]
# Add everything OpenCV build needs
nixPkgs = ["git" "cmake" "make" "pkg-config" "gcc" "g++" "python3"]

[phases.install]
# Standard npm install
cmds = [
  "npm install"
]

[phases.build]
# Rebuild OpenCV after npm install
cmds = [
  "npx opencv-build-npm rebuild --jobs max"
]

[start]
cmd = "npm start"
