[phases.setup]
nixPkgs = ["cmake", "make", "pkg-config", "gcc", "g++", "python3"]

[phases.install]
cmds = [
    "apt-get update && apt-get install -y git",  # <-- ensures git exists
    "git --version",
    "npm install"
]

[phases.build]
cmds = ["npx opencv-build-npm rebuild --jobs max"]

[start]
cmd = "npm start"
